document.addEventListener("DOMContentLoaded", () => {
    const idiomaSelect = document.getElementById("idioma-select")
  
    // Objeto con las traducciones
    const traducciones = {
      es: {
        inicio: "Inicio",
        productos: "Productos",
        acercaDe: "Acerca de nosotros",
        carrito: "Carrito",
        login: "Iniciar sesión",
        bienvenido: "Bienvenido a nuestra tienda de motos",
        explora: "Explora nuestra colección de motocicletas de alta gama.",
        derechos: "Todos los derechos reservados.",
        anadirAlCarrito: "Añadir al carrito",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "Una moto deportiva con gran potencia.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "Alta velocidad y rendimiento para los amantes de la adrenalina.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Diseño aerodinámico y potencia inigualable.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Diseño agresivo y con gran potencia",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extremadamente rápida, colores únicos, potencia abismal",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baja, perfecta para ciudad y trayectos largos",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baja, perfecta para ciudad y trayectos largos",
        iniciarSesion: "Iniciar sesión",
        registro: "Registro",
        nombre: "Nombre",
        dni: "DNI",
        correoElectronico: "Correo electrónico",
        cuentaBancaria: "Cuenta bancaria",
        telefono: "Número de teléfono",
        contrasena: "Contraseña",
        iniciarSesionBtn: "Iniciar sesión",
        registrarBtn: "Registrar",
      },
      en: {
        inicio: "Home",
        productos: "Products",
        acercaDe: "About Us",
        carrito: "Cart",
        login: "Login",
        bienvenido: "Welcome to our motorcycle store",
        explora: "Explore our collection of high-performance motorcycles.",
        derechos: "All rights reserved.",
        anadirAlCarrito: "Add to Cart",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "A sporty bike with great power.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "High speed and performance for adrenaline lovers.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Aerodynamic design and unmatched power.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Aggressive design and absolute comfort, perfect for city rides",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Aggressive design with great power",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Great power, aerodynamic and fast, perfect for exciting routes",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extremely fast, unique colors, immense power",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Comfortable, low, perfect for city and long rides",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Comfortable, low, perfect for city and long rides",
        iniciarSesion: "Log In",
        registro: "Register",
        nombre: "Name",
        dni: "ID",
        correoElectronico: "Email",
        cuentaBancaria: "Bank Account",
        telefono: "Phone Number",
        contrasena: "Password",
        iniciarSesionBtn: "Log In",
        registrarBtn: "Register",
      },
      fr: {
        inicio: "Accueil",
        productos: "Produits",
        acercaDe: "À propos de nous",
        carrito: "Panier",
        login: "Connexion",
        bienvenido: "Bienvenue dans notre magasin de motos",
        explora: "Explorez notre collection de motos haute performance.",
        derechos: "Tous droits réservés.",
        anadirAlCarrito: "Ajouter au panier",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "Une moto sportive avec une grande puissance.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "Grande vitesse et performance pour les amateurs de sensations fortes.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Design aérodynamique et puissance inégalée.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Design agressif et confort absolu, parfait pour les trajets en ville",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Design agressif avec une grande puissance",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Grande puissance, aérodynamique et rapide, parfaite pour les itinéraires passionnants",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extrêmement rapide, couleurs uniques, puissance abyssale",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Confortable, basse, parfaite pour la ville et les longs trajets",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Confortable, basse, parfaite pour la ville et les longs trajets",
        iniciarSesion: "Se connecter",
        registro: "S'inscrire",
        nombre: "Nom",
        dni: "ID",
        correoElectronico: "Email",
        cuentaBancaria: "Compte bancaire",
        telefono: "Numéro de téléphone",
        contrasena: "Mot de passe",
        iniciarSesionBtn: "Se connecter",
        registrarBtn: "S'inscrire",
      },
      de: {
        inicio: "Startseite",
        productos: "Produkte",
        acercaDe: "Über uns",
        carrito: "Warenkorb",
        login: "Anmelden",
        bienvenido: "Willkommen in unserem Motorraddladen",
        explora: "Entdecken Sie unsere Sammlung von Hochleistungsmotorrädern.",
        derechos: "Alle Rechte vorbehalten.",
        anadirAlCarrito: "In den Warenkorb",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "Ein Sportmotorrad mit großer Leistung.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "Hohe Geschwindigkeit und Leistung für Adrenalinliebhaber.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Aerodynamisches Design und unvergleichliche Leistung.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Aggressives Design und absoluter Komfort, perfekt für die Stadtfahrt",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Aggressives Design mit großer Leistung",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Große Leistung, aerodynamisch und schnell, perfekt für aufregende Strecken",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extrem schnell, einzigartige Farben, enorme Leistung",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Bequem, niedrig, perfekt für Stadtfahrten und lange Strecken",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Bequem, niedrig, perfekt für Stadtfahrten und lange Strecken",
        iniciarSesion: "Anmelden",
        registro: "Registrieren",
        nombre: "Name",
        dni: "ID",
        correoElectronico: "E-Mail",
        cuentaBancaria: "Bankkonto",
        telefono: "Telefonnummer",
        contrasena: "Passwort",
        iniciarSesionBtn: "Anmelden",
        registrarBtn: "Registrieren",
      },
      ca: {
        inicio: "Inici",
        productos: "Productes",
        acercaDe: "Sobre nosaltres",
        carrito: "Cistella",
        login: "Iniciar sessió",
        bienvenido: "Benvingut a la nostra botiga de motos",
        explora: "Explora la nostra col·lecció de motocicletes d'alt rendiment.",
        derechos: "Tots els drets reservats.",
        anadirAlCarrito: "Afegir a la cistella",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "Una moto esportiva amb gran potència.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "Alta velocitat i rendiment per als amants de l'adrenalina.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Disseny aerodinàmic i potència inigualable.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Disseny agressiu i confort absolut, perfecte per anar per la ciutat",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Disseny agressiu i amb gran potència",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Gran potència, aerodinàmica i ràpida, perfecta per a rutes plenes d'emoció",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extremadament ràpida, colors únics, potència abismal",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baixa, perfecta per a la ciutat i trajectes llargs",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baixa, perfecta per a la ciutat i trajectes llargs",
        iniciarSesion: "Iniciar sessió",
        registro: "Registre",
        nombre: "Nom",
        dni: "DNI",
        correoElectronico: "Correu electrònic",
        cuentaBancaria: "Compte bancari",
        telefono: "Telèfon",
        contrasena: "Contrasenya",
        iniciarSesionBtn: "Iniciar sessió",
        registrarBtn: "Registrar",
      },
      gl: {
        inicio: "Inicio",
        productos: "Produtos",
        acercaDe: "Sobre nós",
        carrito: "Cesta",
        login: "Iniciar sesión",
        bienvenido: "Benvido á nosa tenda de motos",
        explora: "Explora a nosa colección de motocicletas de alto rendemento.",
        derechos: "Todos os dereitos reservados.",
        anadirAlCarrito: "Engadir á cesta",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "Unha moto deportiva cunha gran potencia.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "Alta velocidade e rendemento para os amantes da adrenalina.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "Deseño aerodinámico e potencia inigualable.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "Deseño agresivo e comodidade absoluta, perfecta para ir pola cidade",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "Deseño agresivo e cunha gran potencia",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "Gran potencia, aerodinámica e rápida, perfecta para rutas cheas de emoción",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "Extremadamente rápida, cores únicas, potencia abismal",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baixa, perfecta para cidade e trayectos longos",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "Cómoda, baixa, perfecta para cidade e trayectos longos",
        iniciarSesion: "Iniciar sesión",
        registro: "Rexistro",
        nombre: "Nome",
        dni: "DNI",
        correoElectronico: "Correo electrónico",
        cuentaBancaria: "Conta bancaria",
        telefono: "Teléfono",
        contrasena: "Contrasinalo",
        iniciarSesionBtn: "Iniciar sesión",
        registrarBtn: "Rexistrarse",
      },
      zh: {
        inicio: "首页",
        productos: "产品",
        acercaDe: "关于我们",
        carrito: "购物车",
        login: "登录",
        bienvenido: "欢迎来到我们的摩托车商店",
        explora: "探索我们的高性能摩托车系列。",
        derechos: "版权所有。",
        anadirAlCarrito: "添加到购物车",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "一款具有强大动力的运动型摩托车。",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "高速和性能，适合寻求肾上腺素的爱好者。",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "空气动力学设计和无与伦比的动力。",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "激进的设计和绝对舒适，完美适合城市骑行",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "激进设计，强大的动力",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "强大动力，空气动力学设计，快速，适合充满刺激的路线",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "极其快速，独特的颜色，巨大的动力",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "舒适，低矮，适合城市和长途骑行",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "舒适，低矮，适合城市和长途骑行",
        iniciarSesion: "登录",
        registro: "注册",
        nombre: "姓名",
        dni: "身份证",
        correoElectronico: "电子邮件",
        cuentaBancaria: "银行账户",
        telefono: "电话号码",
        contrasena: "密码",
        iniciarSesionBtn: "登录",
        registrarBtn: "注册",
      },
      ko: {
        inicio: "홈",
        productos: "제품",
        acercaDe: "회사소개",
        carrito: "장바구니",
        login: "로그인",
        bienvenido: "우리의 오토바이 가게에 오신 것을 환영합니다",
        explora: "고성능 오토바이 컬렉션을 탐험하세요.",
        derechos: "모든 권리 보유.",
        anadirAlCarrito: "장바구니에 추가",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "강력한 성능을 자랑하는 스포츠 오토바이.",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "아드레날린을 사랑하는 사람들을 위한 고속 성능.",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "공기역학적 디자인과 비할 데 없는 파워.",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "공격적인 디자인과 절대적인 편안함, 도심 주행에 완벽",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "공격적인 디자인과 강력한 성능",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "강력한 성능, 공기역학적 디자인, 빠르고, 짜릿한 여행을 위한 완벽한 오토바이",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "매우 빠르며, 독특한 색상, 강력한 성능",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "편안하고 낮은, 도시와 긴 여행에 적합",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "편안하고 낮은, 도시와 긴 여행에 적합",
        iniciarSesion: "로그인",
        registro: "회원가입",
        nombre: "이름",
        dni: "아이디",
        correoElectronico: "이메일",
        cuentaBancaria: "은행 계좌",
        telefono: "전화번호",
        contrasena: "비밀번호",
        iniciarSesionBtn: "로그인",
        registrarBtn: "회원가입",
      },
      ja: {
        inicio: "ホーム",
        productos: "製品",
        acercaDe: "私たちについて",
        carrito: "カート",
        login: "ログイン",
        bienvenido: "私たちのバイクショップへようこそ",
        explora: "高性能のバイクコレクションをご覧ください。",
        derechos: "すべての権利を保有。",
        anadirAlCarrito: "カートに追加",
        "Honda CB650R": "Honda CB650R",
        "Una moto deportiva con gran potencia.": "大きな力を持つスポーツバイク。",
        "Kawasaki Ninja": "Kawasaki Ninja",
        "Alta velocidad y rendimiento para los amantes de la adrenalina.": "アドレナリン愛好者のための高速性能。",
        "Yamaha R1": "Yamaha R1",
        "Diseño aerodinámico y potencia inigualable.": "空力デザインと比類のないパワー。",
        "KTM Duke 990": "KTM Duke 990",
        "Diseño agresivo y comodidad absoluta, perfecta para ir por ciudad": "アグレッシブなデザインと絶対的な快適さ、街中に最適",
        "Kawasaki Z900": "Kawasaki Z900",
        "Diseño agresivo y con gran potencia": "アグレッシブなデザインと強力な性能",
        "Honda CBR 600RR": "Honda CBR 600RR",
        "Gran potencia, aerodinámica y rápida, perfecta para rutas llenas de emoción": "強力なパワー、空力設計、速さ、エキサイティングなルートに最適なバイク",
        "Suzuki GSX 1000R": "Suzuki GSX 1000R",
        "Extremadamente rápida, colores únicos, potencia abismal": "非常に速く、ユニークなカラー、巨大なパワー",
        "Honda CL500": "Honda CL500",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "快適で低い、街中と長距離の走行に最適",
        "Suzuki GSX 800R": "Suzuki GSX 800R",
        "Cómoda, baja, perfecta para ciudad y trayectos largos": "快適で低い、街中と長距離の走行に最適",
        iniciarSesion: "ログイン",
        registro: "サインアップ",
        nombre: "名前",
        dni: "ID",
        correoElectronico: "メールアドレス",
        cuentaBancaria: "銀行口座",
        telefono: "電話番号",
        contrasena: "パスワード",
        iniciarSesionBtn: "ログイン",
        registrarBtn: "サインアップ",
      }
    }      
    
    idiomaSelect.addEventListener("change", () => cambiarIdioma(idiomaSelect.value));
  
    function cambiarIdioma(idioma) {
      console.log("Cambiando idioma a:", idioma);
  
      if (traducciones[idioma]) {
        document.querySelectorAll("[data-translate]").forEach((element) => {
          const key = element.getAttribute("data-translate");
          if (traducciones[idioma][key]) {
            element.textContent = traducciones[idioma][key];
          }
        });
  
        // Actualizar el título y texto del hero si existen
        const heroTitle = document.querySelector(".hero-title");
        const heroText = document.querySelector(".hero-text");
        if (heroTitle) heroTitle.textContent = traducciones[idioma]["bienvenido"];
        if (heroText) heroText.textContent = traducciones[idioma]["explora"];
  
        // Actualizar el footer
        const footerText = document.querySelector(".footer-text");
        if (footerText) {
          const year = new Date().getFullYear();
          footerText.textContent = `© ${year} Tienda de Motos. ${traducciones[idioma]["derechos"]}`;
        }
  
        // Actualizar el contenido del popup si está abierto
        if (document.getElementById("popup").classList.contains("show")) {
          translatePopupContent();
        }
      }
    }
  
    // Inicializar el idioma basado en la selección actual
    cambiarIdioma(idiomaSelect.value);
});
  
// Función para traducir el contenido del popup
function translatePopupContent() {
    const idioma = document.getElementById("idioma-select").value;
    const popupTitle = document.getElementById("popup-title");
    const popupDesc = document.getElementById("popup-desc");
    const addToCartButton = document.querySelector(".popup-info button");
  
    if (popupTitle && popupDesc && addToCartButton && traducciones[idioma]) {
      // Traducir el título si existe una traducción
      if (traducciones[idioma][popupTitle.textContent]) {
        popupTitle.textContent = traducciones[idioma][popupTitle.textContent];
      }
  
      // Traducir la descripción si existe una traducción
      if (traducciones[idioma][popupDesc.textContent]) {
        popupDesc.textContent = traducciones[idioma][popupDesc.textContent];
      }
  
      // Traducir el botón "Añadir al carrito"
      addToCartButton.textContent = traducciones[idioma]["anadirAlCarrito"];
    }
}
  
// Exponer la función globalmente para que pueda ser llamada desde code.js
window.translatePopupContent = translatePopupContent;